### ISSUE TITLE
Error at importing pydantic

### ISSUE THREAD

**Issue by hughqlee** [andylow92/lambda-function-openai-api-2024#1]
Tried with your layer .zip file, but got error as below;
Can you help me solving it, please?

""" error
Response
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'pydantic_core._pydantic_core'",
  "errorType": "Runtime.ImportModuleError",
"""

**Comment by andylow92** [comment]
Remember that the lambda configuration needs to be.
python3.10 | x86_64

Are you using this same configuration?

**Comment by Henry-Hyunkyu-Lee** [comment]
Solved. missed the python version.
Thanks!

**Comment by hughqlee** [comment]
Solved. I missed that the python version should be 3.10.
Thanks!

**Comment by hughqlee** [comment]
Solved. I missed that the python version should be 3.10.
Thanks!

**Comment by andylow92** [comment]
Happy to hear it works!.

**Comment by victor3rc** [comment]
I am getting this error, even though my lambda config is `python3.10 | x86_64` - any ideas?

**Comment by andylow92** [comment]
did you build the lambda layer yourself?

**Comment by victor3rc** [comment]
Nop, I downloaded it from your repo ([here](https://github.com/andylow92/lambda-function-openai-api-2024/tree/main/lambda-layer)).

Happy to share the lambda function’s config, if it helps. It was originally using `python3.11` and I updated it to 3.10, and the architecture I didn’t touch and has been set to `x86_64`

**Comment by Unknown-Turtle** [comment]
> Nop, I downloaded it from your repo ([here](https://github.com/andylow92/lambda-function-openai-api-2024/tree/main/lambda-layer)).
> 
> Happy to share the lambda function’s config, if it helps. It was originally using `python3.11` and I updated it to 3.10, and the architecture I didn’t touch and has been set to `x86_64`

This worked for me:
Make sure all architectures are x86_64 (Lambda function, Lambda layer, and EC2). SSH into your EC2 instance and make a Docker container with the same Python version as your Lambda runtime (I did python:3.10-bullseye). Inside the container, install your packages, zip the folder, then copy the zip from the container to your EC2 instance. then finally, upload the zip as a Lambda layer.

I chose to do it in my ec2 because I'm on Mac.
